### ISSUE TITLE
Symbola is not a free font

### ISSUE THREAD

**Issue by rekado** [MorbZ/OpenSansEmoji#4]
The license for Symbola does not seem compatible with the license of OpenSansEmoji.  Is there an alternative to using glyphs from Symbola?

**Comment by MorbZ** [comment]
The Symbola version used was licensed under ["free for any use"](http://web.archive.org/web/20171227230122/http://users.teilar.gr/~g1951d/). Apparently they changed it but as OpenSansEmoji didn't change it should work with the old license, although I'm not a lawyer.

**Comment by rekado** [comment]
You are right.  This appears to have been changed after January 2018.  Thanks for confirming that the copy of Symbola used in OpenSansEmoji is from a time before the license change, and sorry for the noise!
